version: '3'

services:
   db:
      image: mongo
      ports:
         - "27017:27017"
      volumes:
         - "./mongodata:/data/db"
      networks:
         - mongo-go

   app:
      build: .
      ports: 
        - "54387:54387"
      depends_on:
        - db
      environment:
         PORT: "54387"
      networks:
        - mongo-go

volumes: 
   mongodata: {}

networks: 
   mongo-go: